# Generated by Django 5.2.4 on 2025-07-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('intelligence', models.IntegerField(null=True)),
                ('strength', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('power', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'heroes',
            },
        ),
    ]
